### ISSUE TITLE
TypeError: Cannot read property 'highestRole' of undefined

### ISSUE THREAD

**Issue by matthew-goldman** [andyman1222/ThanosBot#3]
Using node.js v11.12.0 on centos7. Configured the bot with my info, but I'm not sure what to put for `id` - I've tried the Thanos role ID, the user ID, a whole bunch of stuff:

```
{
  "token": "bleh",
  "id": "<what id?>",
  "prefix": "Thanos ",
...
```

Regardless, it starts as expected:
```
$ node app.js                                                        
Bot has started, with 145 users, in 34 channels of 1 guilds.
```

However when I go to ban my test-bot, it fails:
```
Thanos ban @test-bot
```
```
Bot has started, with 145 users, in 34 channels of 1 guilds.
(node:21595) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'highestRole' of undefined
    at Client.client.on (/home/user/bots/ThanosBot/app.js:39:25)
    at Client.emit (events.js:197:13)
    at MessageCreateHandler.handle (/home/user/bots/ThanosBot/node_modules/discord.js/src/client/websocket/packets/handlers/MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (/home/user/bots/ThanosBot/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:103:65)
    at WebSocketConnection.onPacket (/home/user/bots/ThanosBot/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:333:35)
    at WebSocketConnection.onMessage (/home/user/bots/ThanosBot/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:296:17)
    at WebSocket.onMessage (/home/user/bots/ThanosBot/node_modules/discord.js/node_modules/ws/lib/event-target.js:120:16)
    at WebSocket.emit (events.js:197:13)
    at Receiver._receiver.onmessage (/home/user/bots/ThanosBot/node_modules/discord.js/node_modules/ws/lib/websocket.js:137:47)
    at Receiver.dataMessage (/home/user/bots/ThanosBot/node_modules/discord.js/node_modules/ws/lib/receiver.js:409:14)
(node:21595) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:21595) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by matthew-goldman** [comment]
Never mind. I stopped the bot, let it go to offline mode, used the Thanos user ID and it works.
